services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy

  frontend:
    image: "${FRONTEND_IMAGE}"
    container_name: "${FRONTEND_CONTAINER}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:80/"]
      interval: 5s
      timeout: 10s
      retries: 5

  backend:
    image: "${BACKEND_IMAGE}"
    container_name: "${BACKEND_CONTAINER}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:80"]
      interval: 5s
      timeout: 10s
      retries: 5
      