version: "3"

includes:
  dev:
    dir: .
    taskfile: ./Taskfile.dev.yml
    reqired: false

  prod:
    dir: .
    taskfile: ./Taskfile.prod.yml
    reqired: false

tasks:
  generate-ssl:
    desc: Generate SSL certificates
    vars:
      DOMAIN: "localhost"
      COUNTY: "US"
      STATE: "California"
      CITY: "San Francisco"
      ORG: "Example Inc."
      EMAIL: "support@{{.DOMAIN}}"

      CERT_DIR: "./ssl"
      KEY_FILE: "{{.CERT_DIR}}/key.pem"
      CERT_FILE: "{{.CERT_DIR}}/cert.pem"
    cmds:
      - mkdir -p ./ssl
      - openssl req
        -x509
        -nodes
        -days 365
        -newkey rsa:2048
        -keyout {{.KEY_FILE}}
        -out {{.CERT_FILE}}
        -subj "/C={{.COUNTY}}/ST={{.STATE}}/L={{.CITY}}/O={{.ORG}}/CN={{.DOMAIN}}/emailAddress={{.EMAIL}}"
